name: Project validation

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
          npm run build
  validate_hacs:
    name: Validate HACS requirements
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"

  validate_hassfest:
    name: Validate with Hassfest for Home assistant
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: home-assistant/actions/hassfest@master

  control_style:
    name: Check style formatting
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.x"
      - run: python3 -m pip install black
      - run: black .

  # UNIT Test still need to be reviewed and implemented

  # run_tests:
  #   name: Run unit tests
  #   runs-on: "ubuntu-latest"
  #   strategy:
  #     max-parallel: 4
  #     matrix:
  #       python-version: [3.8]
  #   steps:
  #     - name: Check out code from GitHub
  #       uses: "actions/checkout@v2"

  #     - name: Setup Python ${{ matrix.python-version }}
  #       uses: "actions/setup-python@v1"
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Install requirements
  #       run: |
  #         python3 -m pip install --upgrade pip
  #         python3 install -r requirements.prectest.txt

  #     - name: Run tests
  #       run: |
  #         pytest \
  #           -qq \
  #           --timeout=9 \
  #           --durations=10 \
  #           -n auto \
  #           --cov custom_components.auto_areas \
  #           -o console_output_style=count \
  #           -p no:sugar \
  #           tests